# Generated by Django 6.0 on 2025-12-30 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_alter_customuser_role_branch_shipment_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierstaff',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='courier.courierstaff'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courierstaff',
            name='assigned_shipments',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to='courier.shipment'),
        ),
        migrations.AlterField(
            model_name='courierstaff',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='courier.branch'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('super_manager', 'Super Manager / HR'), ('manager', 'Manager'), ('staff', 'Courier Staff'), ('customer', 'Customer')], default='customer', max_length=20, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='courier.shipment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='courier.branch'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_warehouse', 'In Warehouse'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_warehouse', 'In Warehouse'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='courier.shipment')),
            ],
        ),
    ]
