# Generated by Django 6.0 on 2025-12-31 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_courierstaff_is_available_shipment_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='service_type',
            field=models.CharField(choices=[('same_day', 'Same Day'), ('overnight', 'Overnight'), ('economy', 'Economy'), ('international', 'International')], default='economy', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=20)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier.shipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('same_day', 'Same Day'), ('overnight', 'Overnight'), ('economy', 'Economy'), ('international', 'International')], max_length=20)),
                ('weight_from', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight_to', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='courier.branch')),
            ],
        ),
    ]
